# SDG 5: Gender Equality

Sustainable Development Goal 5 is deeply interwoven with SDG 4. The main goal of SDG 5 is to “achieve gender equality and empower all women and girls” (Manzano 2021). The United Nations points out that gender bias limits our human potential by denying half of the world’s population with proper opportunities. SDG 5 is critically important because without gender bias and prejudice, all nations and populations would benefit (The Global Goals, n.d.). Similar to SDG 4, the goal of gender equality has various targets to be reached. (5.1) End discrimination
against women and girls, (5.2) End all violence against and exploitation of
women and girls, (5.3) Eliminate forced marriages and genital mutilations, (5.4)
Value unpaid care and promote shared domestic responsibilities, (5.5) Ensure
full participation in leadership and decision-making, (5.6) Universal access to
reproductive health and rights, (5.7) Equal rights to economic resources,
property ownership and financial services, (5.8) Promote empowerment of women
through technology, (5.9) Adopt and strengthen policies and enforceable
legislation for gender equality (The Global Goals, n.d.).

The year 2024 was a super election year and many communities and advocacy groups were hoping to see more women representation in politics. Though the elections provided ample opportunity to many women, the super election year actually did very little for gender parity (United Nations, n.d.). It is reported that as of January 2024, 27.2% of national parliament seats were held by women. This report provides little progress given only a 0.3 point increase in political representation from 2025. Though since 2015, representation of women in national parliament seats has increased by 4.9 points (United Nations, n.d.). Something very interesting yet frightening happened during this super election year in 2024. During this year, nearly 1 in 4 countries reported a “backlash” against women’s rights (UN Women 2025). This is concerning given that much of the progress made for gender equality before 2024 was lost. Many women also live near dangerous conflict regions, further intensifying pre-existing gender norms and roles. It is reported that in 2023, nearly 612 million women and girls lived within 50 kilometers from an active conflict zone (UN Women 2025). With this in mind, the United Nations have also proved that peace typically lasts longer when women’s voices are heard in the decision-making process (UN Women 2025).
