# Conclusion

The seventeen Sustainable Development Goals allow for conversation, advocacy, and action to take place in a productive way. Specifically, SDG 4 (quality education) and SDG 5 (gender equality) are deeply connected. Gender disparities and a lack of equality are embedded in the roots of quality education throughout the world. While boys have the privilege of going to school, boosting their likelihood of success, women and girls in many regions of the world are forced to stay at home (Charity:Water, n.d.). Not only are girls forced to stay at home and conduct domestic activities, but in many cases, girls will walk miles and miles to fetch water for their household (Charity:Water, n.d.). Keep in mind, this is all while their male counterparts are advancing their learning skills while being at school. Results from a lack of quality education typically impacts women and girls at a much higher rate than men and boys. 

Civilization has been dealing with these issues for all of human history yet right now, with the help of the Sustainable Development Goals, vast progress can be made. One data story is not enough to truly understand these complex issues which is why I will continue working on this project throughout the rest of the semester. Data Story 6 will go into more detail regarding these key issues (quality education and gender equality). My final data story will provide various graphing elements, plots, tables, and a discussion based analysis to further both my own and the viewers understanding of these problems. By focusing on SDG 4 and SDG 5, it is evident that both goals can reinforce one another, creating room for growth to occur. One of the leading drivers of gender inequality is a lack of equally accessible quality education for all children. What is holding women and girls back from receiving a quality education? How can the global community push for better quality education in all regions of the world? In my final project, data story 6, these difficult questions will be tackled and a clear analysis will hopefully come to the surface.
