--- 
title: "Data-Story-3"
author: "Walker Briggs"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    config:
      sharing:
        facebook: false
        twitter: false
documentclass: book
bibliography: [bibliography.bib]
biblio-style: apalike
link-citations: yes
github-repo: https://github.com/ericmkeen/bookdown_minimal
description: "DESCRIPTION yall."
---

# Sustainable Development Goals

The Sustainable Development Goals provide an action driven framework to help tackle some of the most pressing issues in society today. In total, there are seventeen goals that range from local issues to global issues. For Data Story 3 and for the final project, Sustainable Development Goals number 4 and  5 will be of focus. SDG 4 represents quality education and SDG 5 represents gender equality. These two Sustainable Development Goals go hand-in-hand with each other and analyzing them separately would be counterproductive.

The United Nations Conference on Sustainable Development in Rio de Janeiro in 2012 was a critical moment in the creation of the Sustainable Development Goals (UNDP, n.d.). The objective of these seventeen goals was to address current environmental, political, and economic issues. Before the Sustainable Development Goals were established, there were Millennium Development Goals (MDGs) which began in the early 2000s. The MDGs were in place to target “indignity of poverty) (UNDP, n.d.). The SDGs are a more updated version of the MDGs, creating a more aggressive approach to environmental sustainability. 




