# References 
(1) Charity:Water. n.d. “The Water Crisis Is a Women’s Issue.” Charity: Water. Accessed April 9, 2026. https://www.charitywater.org/stories/women-and-water. 


(2) Gongade, Akshata, Anupama Ballur, Aditya Kulkarni, Shivani Pande, Manjunath Unkal, and Nagaraj Navalgund. 2025. “A Bibliometric Analysis on SDG 4: Quality Education.” GSB Insight: Journal of Business and Research 2 (1): 105–17. https://doi.org/10.63141/gijbr-V2N1-2025ID38.

(3) Jiang, Mingxiu. 2025. “Research on the Relationship between Women’s Education and Gender Equality.” Economic Society and Humanities 2 (8): 43–48. https://doi.org/10.62381/E254806. 

(4) Manzano, Irene Rodríguez. 2021. “Gender Equality And Women’s Leadership For Sustainable Development.” European Proceedings of Social and Behavioural Sciences Education in a Changing World: Global Challenges and National Priorities (July). https://doi.org/10.15405/epsbs.2021.07.02.7.

(5) OECD. 2016. “Debate the Issues: New Approaches to Economic Challenges.” OECD Insights 2016 (September). https://doi.org/10.1787/9789264264687-en. 

(6) The Global Goals. n.d. “Goal 4: Quality Education.” The Global Goals. Accessed April 9, 2026. https://globalgoals.org/goals/4-quality-education/. 

(7) UN Women. 2025. “Fifteen Years, Fifteen Facts: Challenges and Solutions for Gender Equality.” UN Women – Headquarters, July 1. https://www.unwomen.org/en/news-stories/press-release/2025/07/fifteen-years-fifteen-facts-challenges-and-solutions-for-gender-equality.

(8) UNDP. n.d. “Background on the Goals.” UNDP. Accessed April 9, 2026. https://www.undp.org/sdg-accelerator/background-goals. 

(9) United Nations. n.d. “THE 17 GOALS | Sustainable Development.” Accessed April 9, 2026. https://sdgs.un.org/goals.

(10) Yadav, Sucheta. 2023. “Gender Equality as a Tool for Sustainable Development.” International Journal of Teaching, Learning and Education 2 (2): 1–3. https://doi.org/10.22161/ijtle.2.2.1.

(11) Ydo, Yao. 2022. “Reaching SDG 4: Our Shared Responsibility and Renewed Commitment to Action.” PROSPECTS 52 (3): 223–29. https://doi.org/10.1007/s11125-022-09628-3.
